### PR TITLE
Asm.js chess demo

### PR DESCRIPTION
**Pull request by joelfillmore**

### CODE REVIEW

**Comment by molant** [comment]
@melanierichards can you take a look please?

Thanks!

**Comment by melanierichards** [comment]
@joelfillmore will take a more thorough look later today but I noticed that the class names are a little off the BEM syntax we're using. Here's where you can find out more about that: http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/

Specifically, let's turn all camelCase in class names to dash-separated lowercase words, and `chess--` is being used to prepend pretty much everything. If you'd like to scope all your classes to a main ancestor `.chess`, you'd instead use `chess__` (underscores for descendants of an element, double dashes for modifications/alternate versions of the element) instead of `chess--`.

**Comment by molant** [comment]
Can we please make all files lower case and update the references in the html?

**Comment by melanierichards** [comment]
General feedback:
- [ ] Found a bug where, using the default settings for the demo in MS Edge, two chess pieces go back and forth b/t two squares in infinity. b1 <=> b2, and a1 <=> c2. Screenshot of the demo while it's having this issue:

chessbug
- [ ] Not sure if related or separate issue to above, but saw this warning in console in MS Edge: "asm.js has been disabled as the script debugger is connected. Disconnect the debugger to enable asm.js." If the demo is dependent on certain browser settings
- [ ] Should debounce the window resize function or similar solution so that the resize event doesn't fire a bunch of times in a row (perf problem when resizing the browser).
- [ ] Somewhere around 1060px and below (until the page layout stacks in one column), the winner position stats start flooding into each other, predicted chance vs. score. You might want to play around with having the two stats stack on top of each other, or having the blocks stack on top of each other. Probably the stats so it's still a comparison of asm.js vs unoptimized js.

**Pull request merged**
