### PR TITLE
Add config and update title and description.

### PR DESCRIPTION
**Pull request by jdalton**
This PR adds some of the things missing to get it published.
Let me know if I need to apply this to another branch.

### CODE REVIEW

**Comment by jdalton** [comment]
Let me know if I need to apply this to another branch.

**Comment by molant** [comment]
Weren't we going to use a different description? Something similar to:
> The Payment Request API was designed with the goal of standardizing communication across merchants, browsers, and payment methods to provide a better experience for users, and a single, consistent API for developers.

@molly26dalton?

Maybe not as long but definitely longer than what we have right now. About 100-150 characters is the ideal length.

**Comment by jdalton** [comment]
I have no preference. Whatever you all want is 👍 
Do you want the title image included somewhere?

**Comment by jdalton** [comment]
Do I include the title image somewhere?

**Comment by molant** [comment]
No need to include the image. @molly26dalton needs to decide about the description for this demo :) (100-150 characters!)

**Comment by jdalton** [comment]
Updated the title and description based on @molly26dalton's feedback.

**Pull request merged**
