### PR TITLE
Add better labels for buttons in `Audio Tuner` demo

### PR DESCRIPTION
**Pull request by alrra**
Fix MicrosoftEdge/Demos#242

---

@dstorey I decided to go with, for example, _"increase microphone base frequency"_ instead of [the suggested](https://github.com/MicrosoftEdge/Demos/issues/242#issue-195704514) _"increase base frequency"_ as it seemed more clear to me. 

Let me know if you want that changed!

### CODE REVIEW

**Comment by alrra** [comment]
@dstorey I decided to go with, for example, _"increase microphone base frequency"_ instead of [the suggested](https://github.com/MicrosoftEdge/Demos/issues/242#issue-195704514) _"increase base frequency"_ as it seemed more clear to me. 

Let me know if you want that changed.

**Review by melanierichards — COMMENTED** [review]
@alrra how this reads out makes sense! I wonder if, following your same principle, it would make sense for the "Microphone" button to read out as "Tune using microphone". Which would impact how you achieve the `aria-labelledby` on the decrease/increase buttons.

Another thought: should the microphone/reference tone be radios instead of buttons? That might streamline the experience (from a general UX perspective, but also tabbing through the buttons), if they're mutually exclusive.

@dstorey your thoughts here?

**Review by sarvaje — APPROVED** [review]

**Review by dstorey — APPROVED** [review]
Looks fine as far as I can tell without running the code. 

The IDs don't follow our naming scheme (we use hyphens rather than camel case, and try to have short IDs) but in this case that would require changing the existing IDs that already didn't follow coding style, so I think it is fine to leave as is for now.

**Comment by dstorey** [comment]
@melanierichards they could be radios, but might be best to just change the minimal needed for now with there being so many a11y issues that need filed and fixed, rather than refactor. From an a11y perspective it shouldn't make much of a difference.

We shouldn't change the labels for the Mic button I don't think, as that would make it clearer when just navigating via controls, but when reading the page linearly it would read the "tune using" heading then read again "tune using microphone" which would be repetitive. With the current labels they should be able to step back to see the label. Neither is really perfect.

**Review by melanierichards — APPROVED** [review]
Per @dstorey's most recent comment, this is good to merge for now.

**Pull request merged**
