### PR TITLE
Associate labels to their controls in Sudoku demo

### PR DESCRIPTION
**Pull request by alrra**
Fix MicrosoftEdge/Demos#235

---

Note: Removed `&nbsp;`s as they were adding extra nodes:

### CODE REVIEW

**Review by sarvaje — APPROVED** [review]
LGTM

**Comment by dstorey** [comment]
@alrra  Can you double check in a screen reader (such as Narrator) that # of games reads out correctly as number of games rather than "hash of games" (en-gb) or "pound of games", as that would be confusing. Maybe we should just be clear and change the label to "number of games" anyway.

**Comment by alrra** [comment]
@dstorey `# of games` reads out as _"hash of games"_ in `Narrator`. 

<a href="https://github.com/MicrosoftEdge/Demos/files/656677/Narrator.zip"></a>

---

> Maybe we should just be clear and change the label to "number of games" anyway.

Done.

**Comment by melanierichards** [comment]
@alrra accidentally overlooked your PR when I restyled the Sudoku demo. Sorry about that!

To get this synced up:

1. Merge in master; take all the new markup.
2. I believe I already have the labels associated with the inputs, but you can update "#" to "Number" and then this PR should be good to go.

**Comment by alrra** [comment]
> Sorry about that!

@melanierichards Don't worry about it. PR should be good to merge now. :)

**Comment by melanierichards** [comment]
Thanks!

**Pull request merged**
