### PR TITLE
Add `<label>` in `Let It Snow` demo

### PR DESCRIPTION
**Pull request by alrra**
Fix MicrosoftEdge/Demos#239

---

### CODE REVIEW

**Review by sarvaje — APPROVED** [review]
It looks good to me

**Review by dstorey — APPROVED** [review]
WFM

**Comment by sarvaje** [comment]
@dstorey What does WFM stand for? hehehe

**Comment by dstorey** [comment]
@sarvaje works for me

**Comment by sarvaje** [comment]
hahaha Thanks!!!
Merging!

**Pull request merged**
