### PR TITLE
Changed sudoku demo to a html demo

### PR DESCRIPTION
**Pull request by sarvaje**

### CODE REVIEW

**Comment by molant** [comment]
@sarvaje you might have to change/delete/do something on the server we decided once this is merged.

**Comment by sarvaje** [comment]
@molant I know, I notice that yesterday when I change the touch effect demo hehehe.

So... is this change ok? or do I wait for the approval of @melanierichards?

**Comment by molant** [comment]
Go ahead and merge

**Comment by sarvaje** [comment]
done!

**Pull request merged**
