### PR TITLE
Use `<button>` instead of `<div>` in `Chess` demo

### PR DESCRIPTION
**Pull request by alrra**
Fix MicrosoftEdge/Demos#192

---

Notes:

   * The uppercase changes are because I've rerun the build process.
   * Made some minor visual changes:

     | Before | After |
     |:---:|:---:|
     |  |  |

### CODE REVIEW

**Review by sarvaje — APPROVED** [review]
LGTM

**Comment by sarvaje** [comment]
@melanierichards or @dstorey can you validate/merge this PR?

**Comment by melanierichards** [comment]
@sarvaje this can be merged after @alrra addresses the comment I left inline about making hex codes lowercase again :]

**Comment by alrra** [comment]
> addresses the comment I left inline 

@melanierichards I don't see any inline comment.

> making hex codes lowercase again :]

Done, but like I said:

> The uppercase changes are because I've rerun the build process.

so next time that build process is run, they will be changed to uppercase again.

---

Maybe we should just drop the `.less` files?

**Review by dstorey — APPROVED** [review]
WFM

**Comment by dstorey** [comment]
@alrra if LESS isn't really used then will be great to drop, but if it is a bunch of work then probably best to focus efforts elsewhere and do a bigger refactor later.

**Comment by alrra** [comment]
> if LESS isn't really used

@dstorey We can just use the generated CSS for now.

> then will be great to drop

This demo has it's own build process, which in my humble opinion should be dropped in favor of a possible a global build process.

**Comment by molant** [comment]
This demo was developed by a third party. It will be great if it didn't had a build process at all...

**Comment by melanierichards** [comment]
Yes, please drop Less and use generated files for now. Thanks!

Sent from Outlook
________________________________

**Comment by alrra** [comment]
> it didn't had a build process at all...

Done!

**Comment by sarvaje** [comment]
@melanierichards is this ready to merge?

**Comment by melanierichards** [comment]
Yup, looks good!

**Pull request merged**
