### PR TITLE
Use `<button>` instead of `<div>` in typedarrays demo

### PR DESCRIPTION
**Pull request by alrra**
Ref MicrosoftEdge/Demos#187
Fix MicrosoftEdge/Demos#187
 
---

Cc @dstorey

### CODE REVIEW

**Comment by alrra** [comment]
Cc @dstorey

**Comment by molant** [comment]
@alrra better ping @sarvaje as well in your PRs, he has superpowers to merge.

**Comment by alrra** [comment]
> @alrra better ping @sarvaje as well in your PRs, he has superpowers to merge.

@molant Sure, thanks!

**Comment by sarvaje** [comment]
LGTM Merging!

**Pull request merged**
