### PR TITLE
Use `<button>` instead of `<div>` in Penguin Mark demo

### PR DESCRIPTION
**Pull request by alrra**
Fix MicrosoftEdge/Demos#182

---

Note: Needed to change some _"button"_ CSS related code (visually it should remain almost the same).

### CODE REVIEW

**Review by sarvaje — APPROVED** [review]
LGTM

**Comment by dstorey** [comment]
Looks good to me. I'm not sure if @molant wants to verify as it is a perf demo. It should be small enough to not run the risks of changing the perf profile for regression testing.

**Comment by molant** [comment]
Should be fine

**Comment by alrra** [comment]
> changing the perf profile 

Note: I did look into that, and didn't see any significant difference.

**Comment by sarvaje** [comment]
Is this ready to merge then?

**Comment by alrra** [comment]
> Is this ready to merge then?

@sarvaje Yes.

**Pull request merged**
